ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  path: /?(.*)
  hosts:
    - grafana.example.live

sidecar:
  datasources:
    enabled: true

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.example.live